[package]
name = "proc-macro-error"
version = "0.2.0"
authors = ["CreepySkeleton <creepy-skeleton@yandex.ru>"]
description = "Drop-in replacement to panics in proc-macros"

repository = "https://github.com/CreepySkeleton/proc-macro-error"
readme = "../README.md"
keywords = ["proc-macro", "error", "errors"]
categories = ["development-tools::procedural-macro-helpers"]
license = "MIT"

edition = "2018"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = "1"
